name: Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION_FILE: app/build.gradle  # Adjust if you're using different build config

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'



    - name: Bump version and push tag
      id: bump-version
      uses: phips28/gh-action-bump-version@v9.0.3
      with:
        commit-message: "ci: bump version to {{version}}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Zip Source Code
      run: |
        zip -r source.zip . -x "*.git*" "*/build/*" "*.gradle*" "*.idea*" "*.iml" "*.apk"

    - name: Upload Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION_TAG }}
        name: Release ${{ env.VERSION_TAG }}
        files: |
          app/build/outputs/apk/release/app-release.apk
          source.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



